server:
  port: 0

spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: ${KAFKA_PORT}

  config:
    import: optional:file:./user/.env[.properties]

  datasource:
    url: ${DATASOURCE_URL}
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

security:
  jwt:
    secret: 54SF5S7F1F3J9W7T888K3R9E3K7E1R3O5K888DFB2D6G5J4D2H5D
    token:
      validity:
        access: 30
        refresh: 15

topic:
  registration: registration
  change:
    password: change_password