version: '3.5'

services:

  eureka-server-service:
    image: junoconnector-eureka-server:latest
    build: eureka_server
    container_name: eureka-server-service
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://localhost:8761" ]
      interval: 5s
      timeout: 5s
      retries: 10

  gateway-service:
    image: junoconnector-gateway-service:latest
    build: gateway
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      EUREKA_URL: http://eureka-server-service:8761/eureka/
    depends_on:
      eureka-server-service:
        condition: service_healthy

  user-service:
    image: junoconnector-user-service:latest
    build: user
    container_name: user-service
    environment:
      DATASOURCE_URL: jdbc:postgresql://user-database:5433/user-db
      eureka.client.serviceUrl.defaultZone: http://eureka-server-service:8761/eureka/
    depends_on:
      eureka-server-service:
        condition: service_healthy
      user-database:
        condition: service_started
  user-database:
    container_name: user-database
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user-db