server:
  port: 0

spring:
  application:
    name: profile-service

  config:
    import: optional:file:./profile/.env[.properties]

  datasource:
    url: ${DATASOURCE_URL}
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${random.uuid}
#  client:
#    service-url:
#      defaultZone: ${EUREKA_URL}
